module.exports = {
  RECEIVED_CURRENT_USER: 'RECEIVED_CURRENT_USER',
  RECEIVED_CURRENT_USER_UPDATE_STATUS_BAD: 'RECEIVED_CURRENT_USER_UPDATE_STATUS_BAD',
  RESET_UPDATE_SUBMISSION_STATUS: 'RESET_UPDATE_SUBMISSION_STATUS',
  TOGGLE_SIGNUP_MODAL_ON: 'TOGGLE_SIGNUP_MODAL_ON'
};
