module.exports = {
  RECEIVE_QUESTIONS: 'RECEIVE_QUESTIONS',
  CHANGE_QUESTION_SORT: 'CHANGE_QUESTION_SORT',
  RECEIVE_QUESTION: 'RECEIVE_QUESTION',
  CHANGE_ANSWER_SORT: 'CHANGE_ANSWER_SORT',
  // SET_TAG_NAME: 'SET_TAG_NAME',
  RECEIVE_QUESTIONS_TAG: 'RECEIVE_QUESTIONS_TAG'
};
