module.exports = {
  RECEIVE_QUESTIONS: 'RECEIVE_QUESTIONS',
  CHANGE_QUESTION_SORT: 'CHANGE_QUESTION_SORT',
  RECEIVE_QUESTION: 'RECEIVE_QUESTION',
  CHANGE_ANSWER_SORT: 'CHANGE_ANSWER_SORT',
  RECEIVE_QUESTIONS_TAG: 'RECEIVE_QUESTIONS_TAG',
  RECEIVE_ANSWER_UPDATE_OK: 'RECEIVE_ANSWER_UPDATE_OK'
};
