module.exports = {
  RECEIVE_TAGS: 'RECEIVE_TAGS',
  CHANGE_TAG_SORT: 'CHANGE_TAG_SORT',
  CHANGE_TAG_SEARCH_TERM: 'CHANGE_TAG_SEARCH_TERM',
  RECEIVE_TAG: 'RECEIVE_TAG',
  RESET_TAG_STORE_SETTINGS: 'RESET_TAG_STORE_SETTINGS'
};
