module.exports = {
  RECEIVE_USERS: 'RECEIVE_USERS',
  CHANGE_USER_SEARCH_TERM: 'CHANGE_USER_SEARCH_TERM',
  RECEIVE_USER: 'RECEIVE_USER',
  CHANGE_USER_POSTS_SORT: 'CHANGE_USER_POSTS_SORT',
  CHANGE_USER_POSTS_SELECT: 'CHANGE_USER_POSTS_SELECT',
  CHANGE_ACTIVITY_SORT_BY: 'CHANGE_ACTIVITY_SORT_BY',
  RECEIVE_USER_SHALLOW: 'RECEIVE_USER_SHALLOW'
};
